### ISSUE TITLE
Colorize (PHP) $variables

### ISSUE THREAD

**Issue by b-ozcan** [rokoroku/vscode-theme-darcula#15]
When using $variable the variable doesn't get a color. In a single line cases it would be ok, but when using in just a little more complex syntax, distinguishing a variable from operators and constants gets hard to read. I know the theme is not intended for PHP, but when this could be implemented, I think PHP would be verry complete too. 

*Red lines are the 'hotspots'.*
![image](https://user-images.githubusercontent.com/26867211/54196249-316b4000-44c1-11e9-83a9-c359b8a6aee8.png)

Thank you for this lovely theme!

**Comment by rokoroku** [comment]
Thanks for your comment!

Unfortunately VSCode cannot distinguish php `as` operator as you expected currently.
Try `Developer: Inspect TM Scope` feature in VSCode and you can see below results:

![스크린샷 2019-03-14 오후 2 23 20](https://user-images.githubusercontent.com/5208632/54402770-9ff20d00-4710-11e9-8d3d-3ebb9200befd.png)
![스크린샷 2019-03-14 오후 2 22 33](https://user-images.githubusercontent.com/5208632/54402771-9ff20d00-4710-11e9-9059-dbb5a6505ea5.png)

They both scoped `keyword.operator.logical` so I can't apply color scheme only for `as` token.
Maybe you can contribute php grammar here?
https://github.com/Microsoft/vscode/blob/master/extensions/php/syntaxes/php.tmLanguage.json


---

Luckily, you can change the `variable` color at least:

Just add below configuration to your VSCode's `settings.json`
```json
{
  "editor.tokenColorCustomizations": {
    "[Darcula]": {
      "textMateRules": [
        {
          "scope": ["variable.other.php"],
          "settings": {
            "foreground": "#9E7BB0"
          }
        }
      ]
    }
  }
}
```
Result:
![스크린샷 2019-03-15 오전 11 58 47](https://user-images.githubusercontent.com/5208632/54405377-b8b2f080-4719-11e9-8a65-4399842703b4.png)

I'm not familiar with the theme of phpStorm yet, but if more people say it should be this theme's default color scheme then I'll follow them.

**Comment by b-ozcan** [comment]
Hi rokoroku,
I wasn't aware of the `Developer: Inspect TM Scope` feature within VS Code and the docs aren't very clear about this kind of features as it seems. Thank you for pointing that out for me! 

As you've suggested I've added some color customizations to my settings.json using that feature. Now the theme look more like my original Darcula theme of PhpStorm v9. 

In case if anyone is wondering, this is what I've added:
```
  "editor.tokenColorCustomizations": {
    "[Darcula]": {
      "textMateRules": [
        {
          "scope": ["variable.language"],
          "settings": {
            "foreground": "#9E7BB0"
          }
        },
        {
          "scope": ["variable.other.property"],
          "settings": {
            "foreground": "#CC8242"
          }
        },
        {
          "scope": ["variable.other.php"],
          "settings": {
            "foreground": "#9E7BB0"
          }
        },
        {
          "scope": ["support.variable.property"],
          "settings": {
            "foreground": "#FFC66D"
          }
        }
      ]
    }
  }
```
<hr />

Is there any possibility that we can customize by language too? Something like:
```
  ...
        {
          "scope": ["variable.other.property"],
          "language": "javascript"
          "settings": {
            "foreground": "#9E7BB0"
          }
  ...
```

**Comment by rokoroku** [comment]
@b-ozcan 
Try `"scope": ["source.js variable.other.property"]`.
You can find the language scope (`source.xx`) via TM inspector too :)

References: 
- https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
- https://macromates.com/manual/en/scope_selectors

**Comment by rokoroku** [comment]
Added in [v1.2.1](https://github.com/rokoroku/vscode-theme-darcula/releases/tag/v1.2.1
)

**Comment by mikrit** [comment]
Say please,

How make global variables (example $_POST) color on VSCode -> #9E7BB0?
