### ISSUE TITLE
JS template strings not recognized properly

### ISSUE THREAD

**Issue by Spence-S** [rokoroku/vscode-theme-darcula#16]
Currently JavaScript template strings are not recognized correctly.

Here is a preview. 

<img width="562" alt="Screen Shot 2019-12-22 at 4 56 21 PM" src="https://user-images.githubusercontent.com/16724951/71327876-05fb9400-24dc-11ea-83c6-1014b2b439d9.png">

Currently the string token scopes are listed like 
```json
 {
      "name": "Strings",
      "scope": "string,string.character.escape,string.template.quoted,string.template.quoted.punctuation,string.template.quoted.punctuation.single,string.template.quoted.punctuation.double,string.type.declaration.annotation,string.template.quoted.punctuation.tag",
      "settings": {
        "foreground": "#6A8759"
      }
    },
    {
      "name": "String Interpolation Begin and End",
      "scope": "punctuation.definition.template-expression.begin,punctuation.definition.template-expression.end",
      "settings": {
        "foreground": "#CC8242"
      }
    },
    {
      "name": "String Interpolation Body",
      "scope": "expression.string,meta.template.expression",
      "settings": {
        "foreground": "#CCCCCC"
      }
    },
```
I was able to fix with the following customizations,
It may be something you want to change in the core theme. 
```json
  "editor.tokenColorCustomizations": {
    "[Darcula]": {
      "textMateRules": [
        {
          "name": "Strings",
          "scope": "string",
          "settings": {
            "foreground": "#6A8759"
          }
        },
        {
          "name": "String Interpolation Begin and End",
          "scope": "punctuation.quasi.element.begin,punctuation.quasi.element.end",
          "settings": {
            "foreground": "#CC8242"
          }
        },
        {
          "name": "String Interpolation Body",
          "scope": "entity.quasi.element,expression.string",
          "settings": {
            "foreground": "#CCCCCC"
          }
        }
      ]
    }
  }
```
which yields 
<img width="559" alt="Screen Shot 2019-12-22 at 5 00 32 PM" src="https://user-images.githubusercontent.com/16724951/71327910-95a14280-24dc-11ea-9cdb-c1b2fc65d76c.png">

and is what _I think_ was originally intended. 

Thanks!

**Comment by rokoroku** [comment]
Hi, I cannot reproduce your issue with my sample case. (it's working well!)
![code](https://user-images.githubusercontent.com/5208632/73416208-81f8bf80-4357-11ea-8b28-98d404684d10.png)

Could you show me more detailed context of the sample code?

**Comment by Spence-S** [comment]
@rokoroku thanks for responding to this - I think I figured out that the problem is that I am using the `babel javascript` language grammar instead of the default `typescript` grammar. It seems its mostly interchangeable but this part is not. Perhaps if you add my customizations to your scopes it would support both :)  - up to you though. I haven't noticed any other problems with using `babel javascript` Happy to submit a PR.
