### ISSUE TITLE
No margin between gutter and editor.

### ISSUE THREAD

**Issue by totsteps** [rokoroku/vscode-theme-darcula#17]
There's no margin between the **Gutter** and the code in editor on left.
#### VSCode
<img width="126" alt="Screenshot 2020-01-11 at 23 20 05" src="https://user-images.githubusercontent.com/6944095/72211322-9587d780-34c9-11ea-8044-76b0b1772ff2.png">

#### WebStorm
<img width="166" alt="Screenshot 2020-01-11 at 23 21 07" src="https://user-images.githubusercontent.com/6944095/72211323-9587d780-34c9-11ea-8ed8-32d74bb1ddbe.png">

**Comment by rokoroku** [comment]
https://code.visualstudio.com/api/extension-guides/color-theme
Unfortunately I couldn't find any padding/margin customization in vscode theme extension guide. Do you have any other resource?

**Comment by totsteps** [comment]
@rokoroku I look into the API and other open-source themes. But haven't found anything. Because of which I am closing this.

Thanks once again.
