### ISSUE TITLE
Background color of 'editorGutter' does not match editor background color

### ISSUE THREAD

**Issue by skjardenCode** [rokoroku/vscode-theme-darcula#18]
Installing the darcula theme on VS Code Version Version: 1.42.1 looks like the following screenshot:

![image](https://user-images.githubusercontent.com/23582335/75292892-646b2880-5825-11ea-901f-bb4211cf3637.png)

I think the background color of the `editorGutter` should match the background color of the editor, like in the [screenshot of the readme](https://github.com/rokoroku/vscode-theme-darcula/blob/master/screenshot.png), for these reasons:

 - It looks more consistent in my opinion
 - All other default themes use the same color for gutter and editor backgrounds
 - The breadcrumb also has the editors background color, making the gutter look a bit out of place

What do you think, should the gutters background color be adjusted accordingly?

If the gutters background color gets changed, I think the sidebars background color must be adjusted, too (darker or lighter).

**Comment by skjardenCode** [comment]
As a suggestion:

```json
"[Darcula]": {
    "editorGutter.background": "#242424",
    "sideBar.background": "#2A2A2A",
    "sideBar.foreground": "#AAAAAA"
}
```

**Comment by rokoroku** [comment]
![image](https://user-images.githubusercontent.com/5208632/75623859-e70f3180-5bf1-11ea-8cde-555b479a3795.png)

I'm afraid I have to disagree with some of your opinion.
I'm trying to make similar to original Darcula theme from Jetbrains'. So,

1. `editorGutter.background` is lighter than editor background color. So I don't want to change it.
2. Make `sideBar.background` lighter is agreed, regardless of the `editorGutter.background` color.
3. Make `sideBar.foreground` darker is not agreed. It seems to undermine the readability. 

If you want to change your workbench color as you want, put your variable settings under `workbench.colorCustomizations` in your `settings.json`(vscode).

![image](https://user-images.githubusercontent.com/5208632/75623950-ee830a80-5bf2-11ea-911d-22b923cd55ba.png)

reference: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

Thanks :)

**Comment by skjardenCode** [comment]
> I'm afraid I have to disagree with some of your opinion.

No problem! This is what opinions are for ;-)

> I'm trying to make similar to original Darcula theme from Jetbrains

I don't know Darcula from Jetbrains much, so you are most certainly better suited for this task than me.

> 1. editorGutter.background is lighter than editor background color. So I don't want to change it.

Thanks for posting the Jetbrains screenshot. In this case, your choosen color for the gutter is correct, of course. I think I was confused because of the screenshot you are using in your README.md (https://github.com/rokoroku/vscode-theme-darcula/raw/master/screenshot.png). There you can see that the gutter background is the same as the editor background, so I assumed the current theme has a bug.

The lighter background of the gutter works well in Jetbrains, because in your screenshot, there is no breadcrumb navigation. In my screenshot there is, so the gutter "gets cut" at the top so to speak. Well, there's probably nothing one can do about it in VS code.


> If you want to change your workbench color as you want, put your variable settings under workbench.colorCustomizations in your settings.json(vscode).

Yes I know these, but thanks for this hint anyway!

**Comment by rokoroku** [comment]
Ok, I'm gonna adjust the breadcrumb and sidebar background color, as well as the screenshot on next update! (that's the first version of this theme 😄)

**Comment by skjardenCode** [comment]
Sorry I forgot one thing, now I remember why I initially wanted the gutter background to match the editor background. Please, see the following screenshot:


![image](https://user-images.githubusercontent.com/23582335/76162501-ab6aef00-613e-11ea-918b-5b8a819a48ee.png)

There you can see that an area of the editor is one pixel too wide. This may be caused by a gutter or editor border?

I think this has nothing to do with your theme (or it has, if it is a border color glitch), but it was my reasoning for suggesting a gutter background change.
