### ISSUE TITLE
Mini color change :)

### ISSUE THREAD

**Issue by bbrakenhoff** [rokoroku/vscode-theme-darcula#2]
Hi!

I really like  your theme and it is really nice to be able to use it in the different editors I use including vscode :). 

I would really happy if you could change the lineHighlight color to the color of the original jetbrains theme (I think it is #323232). Because of this the line I am editing is not highlighted.

Thanks in advance!

**Comment by rokoroku** [comment]
Good, check out [v1.0.8](https://github.com/rokoroku/vscode-theme-darcula/releases/tag/v1.0.8)!

**Comment by bbrakenhoff** [comment]
Looks great, thank you!
