### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by DustInCompetent** [rokoroku/vscode-theme-darcula#22]
I'd like to use this theme in VSCodium. The OpenVSX Extension Library allows suggestions at https://github.com/open-vsx/publish-extensions but requires hosted extensions to have a LICENSE compatible with the Eclipse Public License 2.0. Please consider adding one to this repository.

**Comment by rokoroku** [comment]
Hmm, ok, I'm gonna make it MIT.

**Comment by rokoroku** [comment]
https://github.com/rokoroku/vscode-theme-darcula/commit/4f0a8cf30638196788308eb48efbc5920ba3d239

**Comment by rokoroku** [comment]
btw, do I need to publish it again?

**Comment by DustInCompetent** [comment]
Could you tag that commit as v1.2.2 or something so OVSX can get a grip on it?

To publish to OpenVSX, I'd just update and reopen the pull request mentioned earlier, that would take care of it automatically. But if you want to do it yourself, [this](https://github.com/eclipse/openvsx/blob/master/cli/README.md) is the flow for publishing as a maintainer. Let me know.
