### ISSUE TITLE
Make file bar more contrast

### ISSUE THREAD

**Issue by web2style** [rokoroku/vscode-theme-darcula#3]
Please, have a look at how the file bar looks at your screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/2179726/21266681/429f335e-c3b8-11e6-8361-90c099db0708.png)

And this is how it looks for me:

![asyncinjectors js - first-agenda 2016-12-16 17-46-28](https://cloud.githubusercontent.com/assets/2179726/21266691/4c216ee2-c3b8-11e6-9c43-4643080392dc.png)

Is it how it is expected to look like in the latest version? If so, it is a bit messy in my opinion, can we make it a bit more contrast?

**Comment by rokoroku** [comment]
Sure, recently I changed the background color to match the original theme.
But it seems to overlap much with the window color of the dark base theme.

I'll either revert the change or find a way to improve them soon .

**Comment by rokoroku** [comment]
It seems like there is no way to change default window color, so I decided to revert the background color to the default, and change other colors according to this change. I hope you like it.

**Comment by web2style** [comment]
Yes, thanks. It's perfect now.
