### ISSUE TITLE
Plain text and variables have the same color in JSX

### ISSUE THREAD

**Issue by web2style** [rokoroku/vscode-theme-darcula#4]
![index js - first-agenda 2017-01-02 13-51-46](https://cloud.githubusercontent.com/assets/2179726/21587972/ecebcf38-d0f2-11e6-8b5a-5bfbcc514291.png)

Can we have different colors for them?

**Comment by rokoroku** [comment]
Hmm, I compared with the original theme from WebStorm's and I couldn't find some color scheme for **jsx embedded variable** or **text**.

Do you really need colorize the plain text (or variable)? If so, how about forking this theme and create your own? You can just add a color scheme for ``tsx.children.embedded.expression.variable`` or ``jsx.children.embedded.expression.variable``

**Comment by rokoroku** [comment]
After spending a time, I found there is no syntax for **jsx-tag-children-string** (i.e. plain text) yet. To achieve this, I have to do a lot of work on all the **jsx-tag-attributes** tokens. 

So, the other way is change variable's color within embedded variable, but it doesn't make sense to me. Currently the color of single variable (e.g. ``const content = {...};``) is **white**, and it should not be changed for consistency. (It will harm my readability, IMHO.) 

What's your thoughts on this?

**Comment by web2style** [comment]
I think we can leave it unchanged, not a big deal. Thank you anyway!

**Comment by rokoroku** [comment]
👍 , I'll close this issue :)
