### ISSUE TITLE
Sass highlighting

### ISSUE THREAD

**Issue by yantakus** [rokoroku/vscode-theme-darcula#5]
Sass (scss) code is not highlighted properly, take a look:

![styles scss - lift-v2 2017-03-21 23-34-32](https://cloud.githubusercontent.com/assets/2179726/24169698/7f28cc64-0e8f-11e7-82d4-0c850664f4a9.png)

CSS property values, sass variables, classNames after `&` are not highlighted. Compare it to what I see in WebStorm:

![styles scss - lift-v2 - projects lift-v2 2017-03-21 23-42-11](https://cloud.githubusercontent.com/assets/2179726/24169955/36387666-0e90-11e7-95cc-4562ce3f98a3.png)

Could you please have a look?

**Comment by rokoroku** [comment]
I'll take a look soon :)

**Comment by rokoroku** [comment]
Check out `v1.0.13` from marketplace :)

**Comment by yantakus** [comment]
Thank you very much. But I've found another issue with sass highlighting:

![split scss - lift-v2 2017-04-04 10-46-56](https://cloud.githubusercontent.com/assets/2179726/24646290/11355c8c-1924-11e7-8cb5-1be2d21ea88d.png)

**Comment by yantakus** [comment]
@rokoroku

**Comment by rokoroku** [comment]
<img width="343" alt="2017-04-09 12 23 27" src="https://cloud.githubusercontent.com/assets/5208632/24834418/72ea8b24-1d1f-11e7-9cfb-d594ea335bd4.png">

@yantakus Sorry for late.
`--selector` is scoped as `variable.scss` in vscode's css language service. We'd better post this issue to them.
