### ISSUE TITLE
Difference between single/double quotes

### ISSUE THREAD

**Issue by Khwesten** [rokoroku/vscode-theme-darcula#9]
On Intellij has some diference between quotes.
![image](https://user-images.githubusercontent.com/6913630/37570840-bd9a180c-2ad3-11e8-87fc-6ab575f15e58.png)

**Comment by rokoroku** [comment]
Since I cannot ensure a proper style in all languages, I'm not willing to add the requested style for this theme. 
(Note that this theme is not exactly same with original theme from IntelliJ IDE. There are few modifications to match look and feel with VS Code.)

I'd suggest you try VSCode's own customizing options. 
https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

You can override the specific theme like this:
```json
{
   "editor.tokenColorCustomizations": {
        "[Darcula]": {
            "textMateRules": [
                { 
                    "scope": [
                        "string.quoted.double",
                    ],
                    "settings": {
                        "foreground": "#5f8c3d",
                        "fontStyle": "bold",
                    }
                }
            ]
        }
    }
}
```

Result: 
<img width="367" alt="2018-03-25 5 08 13" src="https://user-images.githubusercontent.com/5208632/37873040-20aba692-304f-11e8-93a6-a8751375b361.png">

**Comment by Khwesten** [comment]
Holy shit, man! Are you crazy!? Thanks a lot!!!

**Comment by Axibord** [comment]
> Since I cannot ensure a proper style in all languages, I'm not willing to add the requested style for this theme.
> (Note that this theme is not exactly same with original theme from IntelliJ IDE. There are few modifications to match look and feel with VS Code.)
> 
> I'd recommend you to try VSCode's own customizing options.
> https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
> 
> You can override the specific style like this:
> 
> ```json
> {
>    "editor.tokenColorCustomizations": {
>         "[Darcula]": {
>             "textMateRules": [
>                 { 
>                     "scope": [
>                         "string.quoted.double",
>                     ],
>                     "settings": {
>                         "foreground": "#5f8c3d",
>                         "fontStyle": "bold",
>                     }
>                 }
>             ]
>         }
>     }
> }
> ```
> 
> Result:
> <img alt="2018-03-25 5 08 13" width="367" src="https://user-images.githubusercontent.com/5208632/37873040-20aba692-304f-11e8-93a6-a8751375b361.png">

I want to same color for text and variables in JS/TS how can I do that ?

**Comment by rokoroku** [comment]
@axibord Turn on `quick menu > Developer: Inspect Editor Tokens and Scopes` feature in VSCode.
Then you can find the corresponding textmate scope like this:
![image](https://user-images.githubusercontent.com/5208632/104598775-5252dc80-56ba-11eb-9d39-83026db634bd.png)

For example, if you want to change above token in screenshot, you can add a rule for `"variable.other.constants"` in your custom theme.

**Comment by PlaymakerQ** [comment]
> @Axibord Turn on `quick menu > Developer: Inspect Editor Tokens and Scopes` feature in VSCode. Then you can find the corresponding textmate scope like this: ![image](https://user-images.githubusercontent.com/5208632/104598775-5252dc80-56ba-11eb-9d39-83026db634bd.png)
> 
> For example, if you want to change above token in screenshot, you can add a rule for `"variable.other.constants"` in your custom theme.

Good advice, thanks.
